name: CI

on: workflow_dispatch

jobs:
  integrity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
